import { useState } from 'react';
import { Bell, ChevronDown, ChevronRight, Copy, Mail, MoreHorizontal, Plus, UserRound } from 'lucide-react';
import { Accordion } from '../../components/ui/Accordion';
import { Alert } from '../../components/ui/Alert';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Card, CardBody, CardHeader } from '../../components/ui/Card';
import { Carousel } from '../../components/ui/Carousel';
import { Collapse } from '../../components/ui/Collapse';
import { ContentNavbar } from '../../components/ui/ContentNavbar';
import { Dropdown } from '../../components/ui/Dropdown';
import { ListGroup } from '../../components/ui/ListGroup';
import { Offcanvas } from '../../components/ui/Offcanvas';
import { PageHeader } from '../../components/ui/PageHeader';
import { Pagination } from '../../components/ui/Pagination';
import { Progress } from '../../components/ui/Progress';
import { Spinner } from '../../components/ui/Spinner';
import { Tabs } from '../../components/ui/Tabs';
import { Tooltip } from '../../components/ui/Tooltip';
import { useToast } from '../../context/ToastContext';

export function UserInterfacePage() {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('overview');
  const [alertVisible, setAlertVisible] = useState(true);
  const [page, setPage] = useState(1);
  const [offcanvasOpen, setOffcanvasOpen] = useState(false);

  return <div className="space-y-6 pb-12">
    <PageHeader title="User Interface" subtitle="Reusable interaction and feedback components for every project." breadcrumbs={[{ label: 'Components' }, { label: 'User Interface' }]} />
    <div className="grid gap-6 xl:grid-cols-2">
      <Card><CardHeader title="Accordion" description="Expandable content areas with keyboard-friendly buttons." /><CardBody><Accordion defaultOpen={['first']} items={[{ id: 'first', title: 'How do I add a new module?', content: 'Add a route, define the menu item in navigation.ts, and connect it to the Laravel permission when the backend is ready.' }, { id: 'second', title: 'Can this be used with Laravel?', content: 'Yes. The menu configuration has permission and feature fields ready to be connected to API data.' }, { id: 'third', title: 'Is nested navigation supported?', content: 'Yes. The sidebar renders child groups recursively, so there is no fixed nesting limit.' }]} /></CardBody></Card>
      <Card><CardHeader title="Alerts" description="Contextual inline feedback with optional dismissal." /><CardBody className="space-y-3">{alertVisible && <Alert variant="success" title="Changes saved" onClose={() => setAlertVisible(false)}>Your workspace preferences are active.</Alert>}<Alert variant="warning" title="Storage notice">You have used 82% of the available storage.</Alert><Alert variant="danger" title="Action required">Reconnect the payment provider to continue.</Alert>{!alertVisible && <Button size="sm" variant="outline" onClick={() => setAlertVisible(true)}>Show dismissed alert</Button>}</CardBody></Card>
      <Card><CardHeader title="Carousel" description="A lightweight, keyboard-accessible slide container for highlights and announcements." /><CardBody><Carousel autoPlayMs={5000} slides={[{ id: 'launch', label: 'Launch update', content: <div className="min-h-40 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-700 p-6 text-white"><p className="text-sm font-medium text-indigo-100">Template update</p><h3 className="mt-2 text-xl font-bold">Build faster with reusable UI.</h3><p className="mt-2 max-w-sm text-sm text-indigo-100">Configure a feature once, then reuse it across every Laravel project.</p></div> }, { id: 'security', label: 'Security update', content: <div className="min-h-40 rounded-xl bg-gradient-to-br from-emerald-600 to-teal-700 p-6 text-white"><p className="text-sm font-medium text-emerald-100">Security</p><h3 className="mt-2 text-xl font-bold">Permission-ready navigation.</h3><p className="mt-2 max-w-sm text-sm text-emerald-100">Show the right modules to the right roles when the backend is connected.</p></div> }]} /></CardBody></Card>
      <Card><CardHeader title="Collapse" description="A compact single-section disclosure for optional content and filters." /><CardBody className="space-y-3"><Collapse title="Advanced filters"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Created after<input type="date" className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label><label className="text-sm">Status<select className="mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800"><option>Any status</option><option>Active</option><option>Archived</option></select></label></div></Collapse><Collapse title="Optional notes" defaultOpen>Keep less-frequently used fields out of the main form while leaving them easy to access.</Collapse></CardBody></Card>
      <Card><CardHeader title="List groups" description="Selectable rows for settings, inboxes, and action menus." /><CardBody><ListGroup items={[{ id: 'profile', title: 'Profile settings', description: 'Name, photo, and contact details', leading: <UserRound className="h-4 w-4" />, trailing: <ChevronRight className="h-4 w-4 text-slate-400" /> }, { id: 'messages', title: 'Unread messages', description: 'You have 3 messages waiting for a reply', leading: <Mail className="h-4 w-4" />, trailing: <Badge variant="primary">3</Badge>, active: true }, { id: 'notifications', title: 'Notifications', description: 'Product updates and activity reminders', leading: <Bell className="h-4 w-4" />, trailing: <ChevronRight className="h-4 w-4 text-slate-400" /> }]} /></CardBody></Card>
      <Card><CardHeader title="Pagination" description="Page navigation with accessible current-page state and ellipsis handling." /><CardBody className="space-y-4"><Pagination page={page} totalPages={12} onChange={setPage} /><p className="text-sm text-slate-500">Showing page <strong className="text-slate-800 dark:text-slate-200">{page}</strong> of 12.</p></CardBody></Card>
      <Card><CardHeader title="Offcanvas" description="A slide-in side panel for details, filters, and quick actions." /><CardBody><Button onClick={() => setOffcanvasOpen(true)}>Open filter panel</Button><Offcanvas open={offcanvasOpen} onClose={() => setOffcanvasOpen(false)} title="Filter orders" footer={<div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => setOffcanvasOpen(false)}>Cancel</Button><Button size="sm" onClick={() => setOffcanvasOpen(false)}>Apply filters</Button></div>}><div className="space-y-5"><p className="text-sm leading-6 text-slate-500">Keep temporary filters and secondary details out of the main workspace.</p><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Order status<select className="mt-2 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-800"><option>All statuses</option><option>Processing</option><option>Completed</option></select></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Customer<input placeholder="Search customer" className="mt-2 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-800" /></label></div></Offcanvas></CardBody></Card>
      <Card><CardHeader title="Spinners" description="Loading states for content, pages, and small inline actions." /><CardBody className="space-y-5"><div className="flex flex-wrap items-center gap-6"><Spinner size="sm" /><Spinner size="md" /><Spinner size="lg" /><Spinner size="xl" /></div><div className="flex flex-wrap items-center gap-5"><Spinner color="primary" label="Saving changes" /><Spinner color="success" label="Processing payment" /><Spinner color="warning" label="Uploading file" /><Spinner color="danger" label="Retrying request" /></div></CardBody></Card>
      <Card className="xl:col-span-2"><CardHeader title="Navbar variants" description="Reusable content-level navigation for pages, modules, and contextual workflows." /><CardBody className="space-y-4"><ContentNavbar brand="Project Atlas" items={[{ id: 'overview', label: 'Overview', active: true }, { id: 'activity', label: 'Activity' }, { id: 'files', label: 'Files' }]} actions={<Button size="sm">Share</Button>} /><ContentNavbar variant="compact" items={[{ id: 'all', label: 'All items', active: true }, { id: 'active', label: 'Active' }, { id: 'archived', label: 'Archived' }]} /><ContentNavbar variant="contextual" brand="Editing product" items={[{ id: 'details', label: 'Details', active: true }, { id: 'pricing', label: 'Pricing' }, { id: 'inventory', label: 'Inventory' }]} actions={<Button size="sm" variant="secondary">Save</Button>} /></CardBody></Card>
      <Card className="xl:col-span-2"><CardHeader title="Typography" description="A clear type scale for application pages, settings, descriptions, and supporting content." /><CardBody className="grid gap-8 lg:grid-cols-2"><div className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Display</p><p className="mt-1 text-4xl font-bold tracking-tight text-slate-900 dark:text-white">Build with clarity</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Page heading</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Workspace settings</h2></div><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Section heading</p><h3 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Notification preferences</h3></div></div><div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Body text</p><p className="mt-1 text-base leading-7 text-slate-600 dark:text-slate-300">Use readable body text for instructions, descriptions, and important product information. Keep sentences direct and focused.</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Supporting text</p><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">Use this for concise labels, helper text, and secondary context.</p></div><div className="flex flex-wrap items-center gap-4 text-sm"><a href="#typography" className="font-semibold text-indigo-600 hover:text-indigo-700 dark:text-indigo-400">Text link</a><code className="rounded bg-slate-100 px-2 py-1 font-mono text-xs text-slate-700 dark:bg-slate-800 dark:text-slate-300">npm run build</code><span className="font-medium text-slate-700 dark:text-slate-200">Medium emphasis</span></div></div></CardBody></Card>
      <Card><CardHeader title="Progress" description="Clear progress feedback for tasks, uploads, and workflows." /><CardBody className="space-y-5"><Progress label="Profile completion" value={72} /><Progress label="File upload" value={46} color="success" size="lg" /><Progress label="Storage used" value={82} color="warning" /><Progress label="Failed records" value={18} color="danger" /></CardBody></Card>
      <Card><CardHeader title="Buttons, badges & tooltips" description="Small reusable controls and clear contextual help." /><CardBody className="space-y-5"><div className="flex flex-wrap gap-2"><Button leftIcon={<Plus className="h-4 w-4" />}>Create new</Button><Button variant="outline">Secondary action</Button><Tooltip content="Copy the generated API token"><Button size="icon" variant="ghost" aria-label="Copy"><Copy className="h-4 w-4" /></Button></Tooltip></div><div className="flex flex-wrap gap-2"><Badge variant="success" dot>Active</Badge><Badge variant="warning">Pending review</Badge><Badge variant="danger">Failed</Badge><Badge variant="info">New</Badge></div></CardBody></Card>
      <Card><CardHeader title="Tabs & dropdowns" description="Organize related content and contextual actions." /><CardBody className="space-y-5"><Tabs variant="pills" activeTab={activeTab} onChange={setActiveTab} tabs={[{ id: 'overview', label: 'Overview' }, { id: 'activity', label: 'Activity', badge: 3 }, { id: 'settings', label: 'Settings' }]} /><p className="text-sm text-slate-500">Selected tab: <strong className="text-slate-800 dark:text-slate-200">{activeTab}</strong></p><Dropdown trigger={<Button variant="outline" size="sm" rightIcon={<ChevronDown className="h-3.5 w-3.5" />}>Actions</Button>} items={[{ label: 'Duplicate', icon: <Copy className="h-4 w-4" />, onClick: () => toast.success('Duplicated', 'A new copy has been created.') }, { label: '', divider: true }, { label: 'Archive', icon: <MoreHorizontal className="h-4 w-4" />, onClick: () => toast.info('Archived', 'The item has been archived.') }]} /></CardBody></Card>
      <Card><CardHeader title="Toast notifications" description="Temporary confirmation and status messages." /><CardBody className="flex flex-wrap gap-2"><Button size="sm" variant="success" onClick={() => toast.success('Saved', 'Your changes are now live.')}>Success toast</Button><Button size="sm" variant="outline" onClick={() => toast.info('New update', 'A fresh report is ready.')}>Info toast</Button><Button size="sm" variant="warning" onClick={() => toast.warning('Check this', 'A required field is incomplete.')}>Warning toast</Button><Button size="sm" variant="danger" onClick={() => toast.error('Unable to save', 'Please try again.')}>Error toast</Button></CardBody></Card>
    </div>
  </div>;
}
